name: digital_diary_app
description: "Дневник"

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.6
  sqflite: any
  path: ^1.8.2
  firebase_core: ^2.0.0
  firebase_auth: ^4.0.0  
  cloud_firestore: ^4.0.0
  shared_preferences: ^2.0.15
  connectivity_plus: ^4.0.0
  pdf: ^3.11.3
  printing: ^5.10.0
  fl_chart: ^1.0.0
  intl: ^0.20.2
  share_plus: ^11.0.0
  csv: ^5.0.0
  simple_heatmap_calendar: ^0.3.0
  table_calendar: ^3.0.9
  file_picker: ^10.1.9
  path_provider: ^2.0.15
  flutter_keyboard_visibility: ^6.0.0
  flutter_typeahead: ^5.0.2
  permission_handler: ^11.3.0
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.4
  geolocator: ^12.0.0
  geocoding: ^2.0.5

  app_theme:
    path: packages/app_theme

  nutrition_tracker:
    path: ../nutrition_tracker

  finance_tracker:
    path: ../finance_tracker

  planner_app:
    path: ../planner_app

  workout_app:
    path: ../workout_app
    
dev_dependencies:
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"

flutter:
  uses-material-design: true
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
        - asset: assets/fonts/NotoEmoji-Regular.ttf
        - asset: assets/fonts/NotoColorEmoji-Regular.ttf
  assets:
    - assets/fonts/
    - assets/icons/app_icon.png
    
