// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdKmwYEP_zmoHY2_yFS3-2uKRxx5NgaWs',
    appId: '1:628560871626:web:9e90b67276271a4dfa7433',
    messagingSenderId: '628560871626',
    projectId: 'diarycloud-5257a',
    authDomain: 'diarycloud-5257a.firebaseapp.com',
    storageBucket: 'diarycloud-5257a.firebasestorage.app',
    measurementId: 'G-0FNCXTJ0EF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKDulJC8k5jW4t1F2Bex8K0sEvJSNLKEo',
    appId: '1:628560871626:android:079b5cecdce51e4afa7433',
    messagingSenderId: '628560871626',
    projectId: 'diarycloud-5257a',
    storageBucket: 'diarycloud-5257a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7em3lm_PlTWTlsNF-mwU2Y_BFOJ-_wAE',
    appId: '1:628560871626:ios:bff27bbc29ad4b72fa7433',
    messagingSenderId: '628560871626',
    projectId: 'diarycloud-5257a',
    storageBucket: 'diarycloud-5257a.firebasestorage.app',
    iosBundleId: 'com.example.digitalDiaryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7em3lm_PlTWTlsNF-mwU2Y_BFOJ-_wAE',
    appId: '1:628560871626:ios:bff27bbc29ad4b72fa7433',
    messagingSenderId: '628560871626',
    projectId: 'diarycloud-5257a',
    storageBucket: 'diarycloud-5257a.firebasestorage.app',
    iosBundleId: 'com.example.digitalDiaryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdKmwYEP_zmoHY2_yFS3-2uKRxx5NgaWs',
    appId: '1:628560871626:web:ef5ce32fa229daaefa7433',
    messagingSenderId: '628560871626',
    projectId: 'diarycloud-5257a',
    authDomain: 'diarycloud-5257a.firebaseapp.com',
    storageBucket: 'diarycloud-5257a.firebasestorage.app',
    measurementId: 'G-NGLCSD17SD',
  );
}
